## NumPy Data Explorer
### Learned NumPy fundamentals – array creation, indexing, and slicing.
### Performed mathematical, axis-wise, and statistical operations on datasets.
### Applied reshaping and broadcasting techniques for efficient computation.
### Implemented save/load operations for NumPy arrays.
### Compared NumPy’s performance with standard Python lists.

In [1]:
import numpy as np

In [2]:
#creating arrays
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)

[1 2 3 4 5 6 7 8]


In [3]:
arr2=np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr3=np.random.randint(1,100,(4,5))
arr3

array([[65, 78, 31, 14, 15],
       [27, 37,  1, 15,  4],
       [76, 97, 70, 24, 83],
       [53, 68,  4, 28, 30]], dtype=int32)

In [9]:
#indexing/ slicing
print("First element: ",arr1[0])
print("Second element: ",arr1[-1])

First element:  1
Second element:  8


In [18]:
#slicing
print("Slice [1:4]: ",arr1[1:4])
print("Slice [:5]: ",arr1[:5])
print("Slice [2:]: ",arr1[2:])
print("Slice [3:-2]: ",arr1[3:-2])

Slice [1:4]:  [2 3 4]
Slice [:5]:  [1 2 3 4 5]
Slice [2:]:  [3 4 5 6 7 8]
Slice [3:-2]:  [4 5 6]


In [20]:
#mathematical operations
print("Addition to array: ",arr1+5)
print("Multiplication to array: ",arr1*2)
print("Square: ",arr1**2)

Addition to array:  [ 6  7  8  9 10 11 12 13]
Multiplication to array:  [ 2  4  6  8 10 12 14 16]
Square:  [ 1  4  9 16 25 36 49 64]


In [22]:
#axis-wise
row_sum=arr3.sum(axis=1)
col_mean=arr3.mean(axis=0)
row_sum,col_mean

(array([203,  84, 350, 183]), array([55.25, 70.  , 26.5 , 20.25, 33.  ]))

In [25]:
#statistical operations
data=np.random.randint(50,100,20)
print("Data: ",data)
print("Mean: ",np.mean(data))
print("Median: ",np.median(data))
print("Standard Deviation: ",np.std(data))
print("Min Value: ",np.min(data))
print("Max Value: ",np.max(data))

Data:  [60 78 51 70 72 93 62 79 86 71 62 79 81 60 80 64 55 85 94 71]
Mean:  72.65
Median:  71.5
Standard Deviation:  11.934299309134156
Min Value:  51
Max Value:  94


In [27]:
#reshaping arrays
reshape=arr2.reshape(2,5)
print(reshape.flatten())

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
#broadcasting
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
v=np.array([10,20,30])
r=m+v
r

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [30]:
arr3

array([[65, 78, 31, 14, 15],
       [27, 37,  1, 15,  4],
       [76, 97, 70, 24, 83],
       [53, 68,  4, 28, 30]], dtype=int32)

In [32]:
#saving
np.save("sample_array.npy",arr3)
l=np.load("sample_array.npy")
l

array([[65, 78, 31, 14, 15],
       [27, 37,  1, 15,  4],
       [76, 97, 70, 24, 83],
       [53, 68,  4, 28, 30]], dtype=int32)